version: '2'
services:
  db: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - python-db

  bot:
    image: bot
    container_name: bot-python
    build:
      context: ./bot
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: python-db   
    restart: on-failure
    networks:
      - python-db
networks:
  python-db: 
    external: true