version: '2'
services:
  db: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

#   # Proxies requests to internal services
#   reverse-proxy:
#     image: nginx:1.17.10
#     container_name: reverse_proxy_demo
#     depends_on:
#         - weather-report
#         - temperature-service
#         - precip-service
#     volumes:
#       - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - 80:80

  # generates weather reports
  # bot:
  #   image: bot
  #   container_name: bot-python
  #   build:
  #     context: ./bot
  #   ports:
  #     - 8080:80
  #   restart: on-failure